import type { PromptAnswers } from "../prompts";

export function webPackageJson(): string {
  return JSON.stringify({
    name: "@app/web",
    version: "0.0.0",
    private: true,
    type: "module",
    scripts: {
      dev: "next dev --port 3000",
      build: "next build",
      start: "next start --port 3000",
    },
    dependencies: {
      "@vitrea/database": "^1.0.1",
      "@internal/web": "workspace:*",
      "drizzle-orm": "^0.43.0",
      next: "^16.0.1",
      react: "^19.1.0",
      "react-dom": "^19.1.0",
    },
    devDependencies: {
      "@tailwindcss/postcss": "^4.1.11",
      "@types/node": "^22.10.2",
      "@types/react": "^19.1.0",
      "@types/react-dom": "^19.1.0",
      tailwindcss: "^4.1.11",
      typescript: "^5.7.2",
    },
  }, null, 2) + "\n";
}

export function webNextConfig(): string {
  return `import type { NextConfig } from "next";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { config as loadDotenv } from "dotenv";

const currentDir = dirname(fileURLToPath(import.meta.url));
loadDotenv({ path: resolve(currentDir, "../../.env") });

const nextConfig: NextConfig = {
  transpilePackages: [
    "@internal/web",
    "@vitrea/render",
    "@vitrea/cms",
    "@vitrea/database",
  ],
};

export default nextConfig;
`;
}

export function webTsconfig(): string {
  return JSON.stringify({
    extends: "../../tsconfig.base.json",
    compilerOptions: {
      jsx: "preserve",
      allowJs: true,
      incremental: true,
      noEmit: true,
      plugins: [{ name: "next" }],
      paths: {
        "@/*": ["./src/*"],
      },
    },
    include: ["next-env.d.ts", "src/**/*.ts", "src/**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  }, null, 2) + "\n";
}

export function webNextEnvDts(): string {
  return `/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is automatically generated by Next.js.
`;
}

export function webPostcssConfig(): string {
  return `export default {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};
`;
}

export function webAppLayout(answers: PromptAnswers): string {
  return `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${answers.projectName}",
  description: "Website for ${answers.projectName}",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;
}

export function webGlobalsCss(): string {
  return `@import "tailwindcss";
@import "@internal/web/styles.css";
`;
}

export function webCatchAllRoute(): string {
  return `import { db, pages } from "@vitrea/database";
import { eq } from "drizzle-orm";
import { PageRenderer, type RenderElement } from "@internal/web";

export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ slug?: string[] }>;
}

export default async function SitePage({ params }: PageProps) {
  const { slug } = await params;
  const siteId = process.env.SITE_ID ?? process.env.WEBSITE_ID;

  if (!siteId) {
    return (
      <div className="flex min-h-screen items-center justify-center text-sm text-white/60">
        SITE_ID or WEBSITE_ID is not configured
      </div>
    );
  }

  const path = "/" + (slug?.join("/") ?? "");
  const normalizedPath = path === "//" ? "/" : path;

  const allPages = await db.select().from(pages).where(eq(pages.siteId, siteId));
  const page = allPages.find((entry) => {
    const data = entry.data as Record<string, unknown> | null;
    return (data?.path as string | undefined) === normalizedPath;
  });

  if (!page) {
    return (
      <div className="flex min-h-screen items-center justify-center text-sm text-white/60">
        Page not found: {normalizedPath}
      </div>
    );
  }

  const renderElements = ((page.pubContent ?? page.content ?? []) as RenderElement[]).map((entry) => ({
    ...entry,
    data: entry.data ?? {},
    styles: entry.styles ?? {},
    children: entry.children ?? [],
  }));

  return <PageRenderer content={renderElements} />;
}
`;
}
